apiVersion: v1
kind: ConfigMap
metadata:
  name: ej10-configmap
  labels:
    app: ej10-configmap
data:
  DEVELOPER: Sebastian Amerio
  CONFIG_LOCATION: /mydata/config.json 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ej10-pingapp
  namespace: curso-kube
  labels:
    app: pingapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pingapp
  template:
    metadata:
      labels:
        app: pingapp
    spec:
      containers:
      - name: pingapp
        image: nicopaez/pingapp:2.1.0
        ports:
        - containerPort: 4567
        envFrom:
          - configMapRef:
              name:  ej10-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: pingapp
  namespace: curso-kube
  labels:
    app: pingapp
spec:
  ports:
   - port: 4567
  selector:
    app: pingapp             
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pingapp
  namespace: curso-kube
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  rules:
  - http:
      paths:
      - path: /pingapp
        pathType: Prefix
        backend:
          service:
            name: pingapp
            port:
              number: 4567