apiVersion: v1
kind: ConfigMap
metadata:
  name: ej10-configmap
  labels:
    app: ej10-configmap
data:
  DEVELOPER: Sebastian Amerio
  CONFIG_LOCATION: /mydata/config.json 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ej10-pingapp
  labels:
    app: pingapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pingapp
  template:
    metadata:
      labels:
        app: pingapp
    spec:
      containers:
      - name: pingapp
        image: nicopaez/pingapp:2.1.0
        ports:
        - containerPort: 4567
        envFrom:
          - configMapRef:
              name:  ej10-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: pingapp
  labels:
    app: pingapp
  annotations:
    dev.okteto.com/auto-ingress: "private"
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: pingapp
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    dev.okteto.com/generate-host: "true"
    dev.okteto.com/private: "false"
  name: pingapp
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: pingapp
          servicePort: 8080
        path: /
