apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:10.4
        ports:
          - containerPort: 5432
        envFrom:
          - secretRef:
              name: secretpostgres 
        volumeMounts:
          - mountPath: "/var/lib/postgresql/data"
            name: "vol-pgdata"
      volumes:
        - hostPath:
            path: "/home/dimi-server/kubernetes/curso_ej9/data"
          name: vol-pgdata